#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by PyTools/AutoVersionFromGIT/AutoVersionFromGIT.py
// Do not modify this file manually
#define VI_VERSION_NICKNAME "Visindigo"
#define VI_VERSION_BUILD 174
#define VI_VERSION_BUILD_DATE "2023-10-01"
#define VI_VERSION_BUILD_TIME "22:07:53"
