#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by PyTools/AutoVersionFromGIT/AutoVersionFromGIT.py
// Do not modify this file manually
#define VI_VERSION_NICKNAME "Visindigo"
#define VI_VERSION_BUILD 179
#define VI_VERSION_BUILD_DATE "2023-10-15"
#define VI_VERSION_BUILD_TIME "11:15:49"
