#pragma once

namespace Visindigo {
	enum Language {
		en_US, zh_SC, zh_TC, ja_JP, ko_KR, fr_FR, de_DE, ru_RU,
		es_ES, es_MX, pt_BR, pt_PT, it_IT, th_TH, vi_VN, id_ID, //the lines under this are generated by copilot
		tr_TR, ms_MY, fil_PH, ar_SA, hi_IN, bn_IN, gu_IN, kn_IN, //I am not sure if they are correct
		ml_IN, mr_IN, ta_IN, te_IN, ne_NP, si_LK, ur_PK, fa_IR,
	};
	enum BehaviorState {
		Idle, Active, Subside
	};
	enum QuantifyTickType {
		T0, T20, T32, T64, T128
	};
	enum BinarySizeUnit { // The number of this enum can't be changed, as it is used in calculation directly
		bit = 1,
		Byte = 8,
		Char = Byte
	};
	enum CountingUnit { // The number of this enum can't be changed, as it is used in calculation directly
		_0 = 1, K, M, G, T, P, E, Z, Y
	};
	enum BinarySizeFormat { // The number of this enum can't be changed, as it is used in calculation directly
		IEC = 1024,
		SI = 1000,
	};
	enum EmphasisSide {
		Left, Top, Right, Bottom, DefaultEmphasis
	};
}