//This document is automatically generated by the SPS parser and will be refreshed every time Visindigo.JS is started. 
//Any changes you make will not be saved.
//此文档由SPS解析器自动生成，每次启动Visindigo.JS之前此文件都会被刷新。
//您的任何更改都不会保存。
export function t10_SPOL() {}

t10_SPOL.__head__ = ["/SPOL0.10.0", 
""];

t10_SPOL.PartA = [">>>:\"Hello, world!\" says the computer.", 
"...", 
""];

