import sys
import os
import datetime

defaultNickName = "Visindigo"
dateNickName = {
    "0401": "我知道有的人喜欢在这种日子往程序里面加点小故障",
    "0410": "噩梦开始的日子",
    "0521": "用歌声将世界染成天蓝色",
    "0601": "你怎么敢讲德克萨斯的坏话",
    "0712": "梦开始的日子",
    "0806": "天雨尽，终作长烟",
    "1224": "多给她烤点苹果派"
}
def getCommitCount():
    gitCommitsCount = os.popen("git log --oneline | find /v /c \"\"").read()
    gitCommitsCount = int(gitCommitsCount)+1
    print("Visindigo commits version now is : "+ str(gitCommitsCount))
    return gitCommitsCount

def nickNameStinger():
    todayStr = datetime.date.today().strftime("%m%d")
    if todayStr in dateNickName:
        print("Today is "+dateNickName[todayStr])
        return dateNickName[todayStr]
    else:
        print("Today is not a special day")
        return defaultNickName

def spawnHeadFile(path):
    if os.path.exists(path+"/Visindigo/VICore/private/VIAutoVersion.h"):
        os.remove(path+"/Visindigo/VICore/private/VIAutoVersion.h")
    versionFile = open(path+"/Visindigo/VICore/private/VIAutoVersion.h", "w", encoding="utf-8-sig")
    versionFile.write("#pragma execution_character_set(\"utf-8\")\n")
    versionFile.write("#pragma once\n")
    versionFile.write("// This file is auto generated by PyTools/AutoVersionFromGIT/AutoVersionFromGIT.py\n")
    versionFile.write("// Do not modify this file manually\n")
    versionFile.write("#define VI_VERSION_NICKNAME \""+nickNameStinger()+"\"\n")
    versionFile.write("#define VI_VERSION_BUILD "+str(getCommitCount())+"\n")
    versionFile.write("#define VI_VERSION_BUILD_DATE \""+datetime.date.today().strftime("%Y-%m-%d")+"\"\n")
    versionFile.write("#define VI_VERSION_BUILD_TIME \""+datetime.datetime.now().strftime("%H:%M:%S")+"\"\n")
    versionFile.close()


if __name__ == "__main__":
    path:str = sys.path[0]
    print(path)
    os.chdir(path+"/../../")
    path = os.getcwd()
    spawnHeadFile(path)



