#pragma execution_character_set("utf-8")
#pragma once
// This file is auto generated by code/VIMiCore/pytools/AutoVersionFromGIT.py
// Do not modify this file manually
#define VI_VERSION_NICKNAME "Visindigo"
#define VI_VERSION_BUILD 188
#define VI_VERSION_BUILD_DATE "2024-09-23"
#define VI_VERSION_BUILD_TIME "22:10:45"
